### PR TITLE
Feat/bug fix

### LINKED ISSUE #43: Fix: Quiz View Button Action
## 🐞 Bug
- 발생 위치: Quiz View
- 발생 조건: 정답을 맞췄을 때 Correct 버튼 연속 클릭
- 증상 설명: Correct 버튼 활성화시 클릭 횟수만큼 인덱스 증가

### PR DESCRIPTION
**Pull request by Juhwa-Lee1023**
## ❇️ Related-issue
- closes #43 

## ✳️ Description
- QuizView bug Fix
- Create PricipleView Sound feat
- Add Buttonhidden

### CODE REVIEW

File: HangulTop/ViewController/QuizViewController.swift [hunk 1]
```diff
@@ -101,6 +102,15 @@ class QuizViewController: UIViewController {
...
     }
+    @IBAction func temp(_ sender: UIButton) {
+        let synthesizer = AVSpeechSynthesizer()
+        let utterance = AVSpeechUtterance(string: sender.titleLabel?.text ?? "")
+        utterance.voice = AVSpeechSynthesisVoice(language: "ko-KR")
+        
+        utterance.rate = 0.6
+        synthesizer.speak(utterance)
+        
+    }
```
Comment (jim4020key) [inline HangulTop/ViewController/QuizViewController.swift:113]: 함수명 ... 바꿔주세요 ... 🥲

Comment (Juhwa-Lee1023) [reply HangulTop/ViewController/QuizViewController.swift]: [f9cc0eb9a52f7440d15832dc7c94cd799ac4698a](https://github.com/DeveloperAcademy-POSTECH/MC3-Team12-HangulTop/pull/49/commits/f9cc0eb9a52f7440d15832dc7c94cd799ac4698a) 
수정 완료

**Review by jim4020key — APPROVED** [review]
수고하셨습니다 👏👏
